# Changing the UUID in this file will make Plan regard your server as a completely new server
# Tread with caution.
Server:
    ID: 1
    UUID: 05b11a68-5dec-4e45-aad5-73cc37e5f4d4
    Web_address: http://localhost:8804
